
platform :ios, '8.0'

target 'ZuJianHuaDemo' do
  
  use_frameworks!
  pod 'AFNetworking', '~> 3.1'
  pod 'FMDB', '~> 2.6'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  pod 'SDWebImage'
  pod 'MQTTClient'
  pod 'Masonry'
  pod 'ReactiveObjC', '~> 3.1.0'
  
end
